print("===================================")
print("PROJET GESTION SCOLAIRE UEH")
print("Structure initiale creee avec succes!")
print("===================================")
print("Modules a implementer :")
print("- Gestion des etudiants")
print("- Gestion financiere")
print("- Interface utilisateur")
print("===================================")